### PR TITLE
Use Tycho 3.0.1

### PR DESCRIPTION
**Pull request by mickaelistria**

### CODE REVIEW

**Comment by fbricon** [comment]
Why do we need Tycho 4 snapshot, and not 3.0.1?

**Comment by mickaelistria** [comment]
We don't strictly need it, but since it's working well and has a lot of nice improvements and is also not compatible with 3.0.0; it's IMO worth adopting it right now.
FWIW, Platform and many others to do use 4.0.0-SNAPSHOT and are happy with it.

**Comment by fbricon** [comment]
Then please don't. Use of snapshots make builds not reproducible in the long term (snapshots tend to disappear as you can see).

**Comment by mickaelistria** [comment]
Tycho 4.0.0-SNAPSHOT is my only offer as I find that sticking to older versions is way more harmful for the project that using snapshots. Don't hesitate to create another PR for Tycho 3.0.1 then.

**Comment by fbricon** [comment]
Fixed to use 3.0.1 and make unit test work

**Pull request merged**
